site_name: Jack Hardy
site_url: https://jackjohnhardy.github.io/
repo_url: https://github.com/JackJohnHardy/jackjohnhardy.github.io
repo_name: jackjohnhardy.github.io
edit_uri: "edit/main/docs"
nav:
  - 'Homepage': index.md
  - 'About Me': about_me.md
  - 'Projects':
    - 'Overview': projects_overview.md
    - 'This Website': website.md
    - 'PiazzaPanic': piazza_panic.md
    - 'Bird Game': bird_game.md
    - 'TerminusRP': terminusrp.md
  - 'CV': CV.md
plugins:
  - glightbox
  - search
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - header.autohide
    - content.tabs.link
  logo: img/JH_Logo.png
  favicon: img/JH_Logo.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode
markdown_extensions:
  - admonition
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true 
extra:
  generator: false
  social:
    - icon: material/email
      link: mailto:jackjohnhardy@outlook.com
      name: 'Email Me'
    - icon: material/web
      link: https://jackjohnhardy.github.io
      name: 'My Website'
    - icon: material/github
      link: https://github.com/JackJohnHardy
      name: 'Jack Hardy on GitHub'
copyright: Copyright &copy; 2022 Jack Hardy